### ISSUE TITLE
Command-line interface noteplan-cli not working anymore

### ISSUE THREAD

**Issue by amaterasu** [NotePlan/plugins#79]
Commands like noteplan-cli plugin:create or plugin:info not working anymore. 

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'lodash.merge'
Require stack:
- /Users/alex/Projects/NotePlan3/plugins/src/utils/app.js
- /Users/alex/Projects/NotePlan3/plugins/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/alex/Projects/NotePlan3/plugins/src/utils/app.js:6:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/alex/Projects/NotePlan3/plugins/index.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/alex/Projects/NotePlan3/plugins/src/utils/app.js',
    '/Users/alex/Projects/NotePlan3/plugins/index.js'
  ]
}
```

Latest working commit is 6747bebebc517facac19c50f3d0636a3021edb8b.

**Comment by mikeerickson** [comment]
Hello @amaterasu 

I have a fix queued up to address this is, but in the meantime, you can resolve this by running 

```
npm install lodash.merge
```

**Comment by amaterasu** [comment]
Hi @mikeerickson 

Thanks for the quick reply and the workaround.

**Comment by mikeerickson** [comment]
@amaterasu No problem, sorry about the issue.   Moving forward, whenever you do a `git pull …` it is always good to run `npm install` as there might be dependency changes, and this will assure you have all the latest `node_modules` installed.
